version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  main:
    jobs:
      - build-and-test

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.8
  
    steps:
      - checkout
      - python/load-cache
      - python/install-packages:
          pkg-manager: pip
      - python/save-cache

      - run:
          name: Run tests
          command: pytest
